### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by tomjpandolfi** [honey-protocol/honey-frontend-solana#262]
## TODOs

- [x]  Periodically fetch data from liquidation API, and store in NextJS for SSR
- [x]  Connect frontend to fetch from NextJS instead of Heroku API
- [x] Borrow / Lend
- [x] Liquidation

**Comment by bowtiedpyro** [comment]
- SSR -> static files generated on build time
- every 30s these static files are being updated
- Liquidations = check
- Borrow and lend works regarding SSR
